-- 
-- PostgreSQL database dump
-- 

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: vector; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;


--
-- Name: EXTENSION vector; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION vector IS 'vector data type and ivfflat and hnsw access methods';


SET default_tablespace = '';
SET default_table_access_method = heap;

--
-- Name: alertas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.alertas (
    id bigint NOT NULL,
    activa boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    descripcion character varying(255) NOT NULL,
    fecha date NOT NULL,
    repetitividad character varying(255) NOT NULL,
    tipo character varying(255) NOT NULL,
    vehiculo_id bigint NOT NULL,
    CONSTRAINT alertas_repetitividad_check CHECK (((repetitividad)::text = ANY ((ARRAY['UNICA'::character varying, 'MENSUAL'::character varying, 'ANUAL'::character varying])::text[]))),
    CONSTRAINT alertas_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['ITV'::character varying, 'ACEITE'::character varying, 'FRENOS'::character varying, 'CUSTOM'::character varying])::text[])))
);


--
-- Name: alertas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.alertas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.alertas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: documentos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.documentos (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    estado character varying(255) NOT NULL,
    mensaje_error character varying(255),
    nombre character varying(255) NOT NULL,
    ruta_almacenamiento character varying(255) NOT NULL,
    tamano_bytes bigint NOT NULL,
    tipo character varying(255) NOT NULL,
    vehiculo_id bigint NOT NULL,
    origen_url character varying(255),
    CONSTRAINT documentos_estado_check CHECK (((estado)::text = ANY ((ARRAY['PROCESANDO'::character varying, 'LISTO'::character varying, 'ERROR'::character varying])::text[]))),
    CONSTRAINT documentos_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['PDF'::character varying, 'TXT'::character varying, 'DOCX'::character varying])::text[])))
);


--
-- Name: documentos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.documentos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.documentos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fragmento_embeddings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fragmento_embeddings (
    fragmento_id bigint NOT NULL,
    embedding public.vector NOT NULL
);


--
-- Name: fragmentos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fragmentos (
    id bigint NOT NULL,
    posicion integer NOT NULL,
    texto character varying(8000) NOT NULL,
    documento_id bigint NOT NULL
);


--
-- Name: fragmentos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.fragmentos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fragmentos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL
);


--
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vehiculos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vehiculos (
    id bigint NOT NULL,
    anio integer NOT NULL,
    combustible character varying(20) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    kilometraje bigint,
    marca character varying(50) NOT NULL,
    matricula character varying(20),
    modelo character varying(100) NOT NULL,
    usuario_id bigint NOT NULL,
    CONSTRAINT vehiculos_combustible_check CHECK (((combustible)::text = ANY ((ARRAY['GASOLINA'::character varying, 'DIESEL'::character varying, 'HIBRIDO'::character varying, 'ELECTRICO'::character varying, 'GLP'::character varying, 'GNC'::character varying])::text[])))
);


--
-- Name: vehiculos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.vehiculos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vehiculos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: alertas alertas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alertas
    ADD CONSTRAINT alertas_pkey PRIMARY KEY (id);


--
-- Name: documentos documentos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documentos
    ADD CONSTRAINT documentos_pkey PRIMARY KEY (id);


--
-- Name: fragmento_embeddings fragmento_embeddings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fragmento_embeddings
    ADD CONSTRAINT fragmento_embeddings_pkey PRIMARY KEY (fragmento_id);


--
-- Name: fragmentos fragmentos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fragmentos
    ADD CONSTRAINT fragmentos_pkey PRIMARY KEY (id);


--
-- Name: vehiculos uk_vehiculo_usuario_marca_modelo_anio; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehiculos
    ADD CONSTRAINT uk_vehiculo_usuario_marca_modelo_anio UNIQUE (usuario_id, marca, modelo, anio);


--
-- Name: usuarios ukkfsp0s1tflm1cwlj8idhqsad0; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT ukkfsp0s1tflm1cwlj8idhqsad0 UNIQUE (email);


--
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- Name: vehiculos vehiculos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vehiculos
    ADD CONSTRAINT vehiculos_pkey PRIMARY KEY (id);


--
-- Name: alertas fk7fokqq6m2g8vvvmg4v6i92fr4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alertas
    ADD CONSTRAINT fk7fokqq6m2g8vvvmg4v6i92fr4 FOREIGN KEY (vehiculo_id) REFERENCES public.vehiculos(id);


--
-- Name: documentos fkfytir544uf33vpvlwa5ixs6wq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documentos
    ADD CONSTRAINT fkfytir544uf33vpvlwa5ixs6wq FOREIGN KEY (vehiculo_id) REFERENCES public.vehiculos(id);


--
-- Name: fragmentos fkqystip0ujfm11t1u9wnbm9mcu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fragmentos
    ADD CONSTRAINT fkqystip0ujfm11t1u9wnbm9mcu FOREIGN KEY (documento_id) REFERENCES public.documentos(id);


--
-- Name: fragmento_embeddings fragmento_embeddings_fragmento_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fragmento_embeddings
    ADD CONSTRAINT fragmento_embeddings_fragmento_id_fkey FOREIGN KEY (fragmento_id) REFERENCES public.fragmentos(id) ON DELETE CASCADE;

--
-- PostgreSQL database dump complete
--